version: "3.3"

x-shared-services: &shared-service
    restart: always
    shm_size: 1gb
    labels:
      - "traefik.enable=true"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 5s
      timeout: 1s
      retries: 20

x-common-services: &default-service
  <<: *shared-service
  image: "model:latest"

x-vllm-services: &vllm-service
  <<: *shared-service
  image: "vllm:latest"

x-large-services: &large-service
  <<: *vllm-service
  environment:
    - MODEL=large/pelevin
    - gpu_fraction=40
  labels:
    - "traefik.http.routers.large.rule=PathPrefix(`/`)"
    - "traefik.http.routers.large.entrypoints=large"
    - traefik.http.services.large.loadbalancer.server.port=8000

x-xl-services: &xl-service
  <<: *vllm-service
  environment:
    - MODEL=xl/pelevin
    - gpu_fraction=40
  labels:
    - "traefik.http.routers.xl.rule=PathPrefix(`/`)"
    - "traefik.http.routers.xl.entrypoints=xl"
    - traefik.http.services.xl.loadbalancer.server.port=8000

x-mig-services: &mig-services
  <<: *vllm-service
  environment:
    - MODEL=mig
    - gpu_fraction=35
  labels:
    - "traefik.http.routers.mig.rule=PathPrefix(`/`)"
    - "traefik.http.routers.mig.entrypoints=mig"
    - traefik.http.services.mig.loadbalancer.server.port=8000

x-lawa-services: &lawa-services
  <<: *vllm-service
  environment:
    - MODEL=lawa
    - gpu_fraction=40
  labels:
    - "traefik.http.routers.lawa.rule=PathPrefix(`/`)"
    - "traefik.http.routers.lawa.entrypoints=lawa"
    - traefik.http.services.lawa.loadbalancer.server.port=8000

# front
services:
  front:
    restart: always
    image: "front:latest"
    container_name: front
    network_mode: host
    depends_on:
#      poetry:
#        condition: service_healthy
      large3:
        condition: service_healthy
      xl5:
        condition: service_healthy
      frida1:
         condition: service_healthy
      mig1:
         condition: service_healthy
      lawa1:
         condition: service_healthy


# traefik 
  traefik:
    restart: always
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.poetry.address=:7000"
      - "--entrypoints.large.address=:7001"
      - "--entrypoints.xl.address=:7002"
      - "--entrypoints.frida.address=:7003"
      - "--entrypoints.mig.address=:7004"
      - "--entrypoints.lawa.address=:7005"
    ports:
      - "7000-7100:7000-7100"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

# poetry model
  # poetry:
  #   <<: *vllm-service
  #   environment:
  #     - MODEL=xl/poetry
  #   labels:
  #     - "traefik.http.routers.poetry.rule=PathPrefix(`/`)"
  #     - "traefik.http.routers.poetry.entrypoints=poetry"
  #     - traefik.http.services.poetry.loadbalancer.server.port=8000
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['0']
  #           capabilities: [gpu]

  # gpt3 XL pelevin
  xl5:
    <<: *xl-service
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

  mig1:
    <<: *mig-services
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

  large3:
    <<: *large-service
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]

  lawa1:
    <<: *lawa-services
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2']
            capabilities: [gpu]

# fred
  frida1:
    <<: *default-service
    environment:
      - MODEL=fred
    labels:
      - "traefik.http.routers.frida.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frida.entrypoints=frida"
      - traefik.http.services.frida.loadbalancer.server.port=8000
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
