FROM vllm/vllm-openai:v0.8.4
USER root

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update
RUN yes | apt install libpq-dev libaio-dev 

COPY req_vllm.txt /opt/app/req.txt
WORKDIR /opt/app
RUN --mount=type=cache,target=/root/.cache/pip pip install -r req.txt
COPY . /opt/app

EXPOSE 8000/tcp

# Override the parent image's ENTRYPOINT
ENTRYPOINT ["uvicorn"]

# Provide default arguments
CMD ["model:app", "--host", "0.0.0.0", "--port", "8000"]

#CMD uvicorn model:app --host 0.0.0.0 --port 8000
