# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ru-gpts',
                'doc_host': 'https://mgrankin.github.io',
                'git_url': 'https://github.com/mgrankin/ru-gpts',
                'lib_path': 'rest'},
  'syms': { 'rest.frida': { 'rest.frida.get_sample': ('frida.html#get_sample', 'rest/frida.py'),
                            'rest.frida.iftoken': ('frida.html#iftoken', 'rest/frida.py')},
            'rest.gen': { 'rest.gen.bad_points': ('gen.html#bad_points', 'rest/gen.py'),
                          'rest.gen.bad_words': ('gen.html#bad_words', 'rest/gen.py')},
            'rest.lawa': { 'rest.lawa.create_token_blocker': ('lawa.html#create_token_blocker', 'rest/lawa.py'),
                           'rest.lawa.get_sample': ('lawa.html#get_sample', 'rest/lawa.py'),
                           'rest.lawa.get_sampling_params': ('lawa.html#get_sampling_params', 'rest/lawa.py'),
                           'rest.lawa.iftoken': ('lawa.html#iftoken', 'rest/lawa.py')},
            'rest.rest_contrastive': { 'rest.rest_contrastive.get_sample': ( 'rest_contrastive.html#get_sample',
                                                                             'rest/rest_contrastive.py')}}}
