# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ru-gpts',
                'doc_host': 'https://mgrankin.github.io',
                'git_url': 'https://github.com/mgrankin/ru-gpts',
                'lib_path': 'rest'},
  'syms': { 'rest.core': { 'rest.core.fix_string': ('core.html#fix_string', 'rest/core.py'),
                           'rest.core.get_ban': ('core.html#get_ban', 'rest/core.py'),
                           'rest.core.init_instance': ('core.html#init_instance', 'rest/core.py'),
                           'rest.core.log': ('core.html#log', 'rest/core.py'),
                           'rest.core.process_seq': ('core.html#process_seq', 'rest/core.py')},
            'rest.rest': {'rest.rest.get_sample': ('rest.html#get_sample', 'rest/rest.py')},
            'rest.rest_contrastive': {'rest.rest_contrastive.get_sample': ('rest_contrastive.html#get_sample', 'rest/rest_contrastive.py')},
            'rest.restxl': {'rest.restxl.get_sample': ('restxl.html#get_sample', 'rest/restxl.py')},
            'rest.storage': {},
            'rest.text': {}}}