# AUTOGENERATED! DO NOT EDIT! File to edit: ../06_frida.ipynb.

# %% auto 0
__all__ = ['model_path', 'seq_length', 'full_path', 'tokenizer', 'model', 'device', 'get_sample']

# %% ../06_frida.ipynb 3
from os import getenv
model_path = getenv("MODEL")
from .gen import generate


# %% ../06_frida.ipynb 5
seq_length = 1024

full_path = f'./models/{model_path}'
import torch
from transformers import GPT2Tokenizer, T5ForConditionalGeneration 
tokenizer = GPT2Tokenizer.from_pretrained(full_path, eos_token='</s>')
model = T5ForConditionalGeneration.from_pretrained(full_path, torch_dtype=torch.bfloat16) 
device='cuda'
model.to(device);
model.eval();


# %% ../06_frida.ipynb 8
from front.common import process_seq

def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    lm_text = '<LM>' + prompt
    input_ids=torch.tensor([tokenizer.encode(lm_text)]).cuda()
    output_ids = model.generate(input_ids, do_sample=True, temperature=.5, repetition_penalty=5.0, typical_p=0.9, top_k=10, top_p=0.95, #watermark=False,
                        max_new_tokens=length, 
                        num_return_sequences=num_samples,)

    result = [tokenizer.decode(o[1:]).replace('\n', ' ') for o in output_ids]
    result = process_seq(result)
    return result

