# AUTOGENERATED! DO NOT EDIT! File to edit: ../06_frida.ipynb.

# %% auto 0
__all__ = ['model_path', 'seq_length', 'full_path', 'tokenizer', 'model', 'device', 'get_sample']

# %% ../06_frida.ipynb 3
from os import getenv
model_path = getenv("MODEL")
from .gen import generate


# %% ../06_frida.ipynb 5
seq_length = 1024

full_path = f'./models/{model_path}'
import torch
from transformers import GPT2Tokenizer, T5ForConditionalGeneration 
tokenizer = GPT2Tokenizer.from_pretrained(full_path, eos_token='</s>')
model = T5ForConditionalGeneration.from_pretrained(full_path, torch_dtype=torch.bfloat16) 
device='cuda'
model.to(device);
model.eval();


# %% ../06_frida.ipynb 9
def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    return generate(model, tokenizer, seq_length, '<LM>' + prompt, length, num_samples, allow_linebreak)
