# AUTOGENERATED! DO NOT EDIT! File to edit: ../06_frida.ipynb.

# %% auto 0
__all__ = ['model_path', 'seq_length', 'full_path', 'tokenizer', 'model', 'line_enders', 'iftoken', 'get_sample']

# %% ../06_frida.ipynb 3
from os import getenv
model_path = getenv("MODEL")

# %% ../06_frida.ipynb 5
from optimum.onnxruntime import ORTModelForSeq2SeqLM

# %% ../06_frida.ipynb 6
seq_length = 1024
seq_length = 512

full_path = f'./models/{model_path}'
import torch
from transformers import (
    AutoTokenizer,
    GPT2Tokenizer,
    LogitsProcessorList,
    T5ForConditionalGeneration,
)
from .sampling import (
    DEFAULT_TEMPERATURE,
    REPETITION_PENALTY,
    TOP_K,
    TOP_NSIGMA,
    TOP_P,
    TopNSigmaLogitsProcessor,
)

# %% ../06_frida.ipynb 9
tokenizer = GPT2Tokenizer.from_pretrained(full_path+'/optimized/', eos_token='</s>')
model = ORTModelForSeq2SeqLM.from_pretrained(full_path+'/optimized/', provider="CUDAExecutionProvider")

# %% ../06_frida.ipynb 12
from .gen import get_line_enders, iftoken

def iftoken(tokenizer, tokens):
    # returns token id if the given string is one token
    token_ids = [tokenizer.encode(token, add_special_tokens=False) for token in tokens]
    return [id for sublist in token_ids for id in sublist if len(sublist) == 1]

# %% ../06_frida.ipynb 13
from front.common import process_seq

line_enders = get_line_enders(tokenizer)

def get_sample(
    prompt,
    length: int,
    num_samples: int,
    allow_linebreak: bool,
    temperature: float = DEFAULT_TEMPERATURE,
):
    max_input = 2*1024 - length
    prompt = tokenizer.decode(tokenizer.encode(prompt)[-max_input:]).removeprefix('<|begin_of_text|>')

    blocked_tokens = ["».",'.\n','\n\t\t','http://',',[','("','.]',' («',')','\u2004',']','(«','[', ' [', '(', ' (', '\xa0', '*', '­', '~', '_', '\\', '\uf04a', '\ufeff', '\u2028']
    if not allow_linebreak:
        blocked_tokens.extend(['\n', '\n\n',' \n'])
    bad_words_ids = iftoken(tokenizer, blocked_tokens)
    bad_words_ids = [[w] for w in bad_words_ids]
    
    lm_text = '<LM>' + prompt
    input_ids=torch.tensor([tokenizer.encode(lm_text)]).cuda()
    torch.cuda.empty_cache()
    output_ids = model.generate(
        input_ids,
        do_sample=True,
        temperature=temperature,
        repetition_penalty=REPETITION_PENALTY,
        top_k=TOP_K,
        top_p=TOP_P,
        logits_processor=LogitsProcessorList(
            [TopNSigmaLogitsProcessor(TOP_NSIGMA)]
        ),
        max_new_tokens=length,
        bad_words_ids=bad_words_ids,
        num_return_sequences=num_samples,
    )
    
    result = [tokenizer.decode(o[1:]).replace('\n', ' ') for o in output_ids]
    result = process_seq(result)
    return result
