# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_gen.ipynb.

# %% auto 0
__all__ = ['bad_points', 'bad_words', 'iftoken', 'get_line_enders', 'TextDataset']

# %% ../02_gen.ipynb 2
def bad_points(tokenizer, point):
    result = []
    for i in range(2, 50):
        code = tokenizer.encode(point*i)
        if len(code) == 1:
            result += [code]
    return result

def bad_words(tokenizer, allow_linebreak):
    bad_symbols = ['[','(','\xa0','*','­', '~', '_', '\\', '\n\n', '\uf04a', '\ufeff', '\u2028']
    bad_words_ids = [tokenizer.encode(s) for s in bad_symbols]

    eot = tokenizer.encode('a<|endoftext|>')[1]
    if eot: bad_words_ids += [[eot]]
    
    for point in ['.','*','_','-','\xa0','!']:
        bad_words_ids += bad_points(tokenizer, point)
    linebreaks = [tokenizer.encode(s) for s in ['\n', ' \n']]
    bad_words_ids += [] if allow_linebreak else linebreaks
    bad_words_ids = [sublist for sublist in bad_words_ids if 50257 not in sublist]
    return bad_words_ids

# %% ../02_gen.ipynb 3
def iftoken(tokenizer, tokens):
    # returns token id if the given string is one token
    token_ids = [tokenizer.encode(token, add_special_tokens=False) for token in tokens]
    return [id for sublist in token_ids for id in sublist if len(sublist) == 1]

def get_line_enders(tokenizer):
    return [tokenizer.decode(token_id) for token, token_id in tokenizer.get_vocab().items() if '\n' in tokenizer.decode(token_id)]

# %% ../02_gen.ipynb 4
from torch.utils.data import Dataset
import torch

class TextDataset(Dataset):
    def __init__(self, path, tokenizer, seq_length=2048):
        with open(path) as f:
            data = f.read()
        tokens = tokenizer.encode(data)
        examples = []
        for i in range(0, len(tokens) - seq_length + 1, seq_length):
            examples.append(tokens[i:i + seq_length])
        self.samples = torch.LongTensor(examples)
        print('Loaded samples:', len(self.samples))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, item):
        return self.samples[item]
