# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_large.ipynb.

# %% auto 0
__all__ = ['model_path', 'seq_length', 'full_path', 'tokenizer', 'model', 'get_sample']

# %% ../03_large.ipynb 3
from os import getenv
model_path = getenv("MODEL")
from .gen import generate


# %% ../03_large.ipynb 5
seq_length = 1024

full_path = f'./models/{model_path}'
import torch
from transformers import GPT2LMHeadModel,GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained(full_path, pad_token_id = 50256)
model = GPT2LMHeadModel.from_pretrained(full_path, torch_dtype=torch.bfloat16)
model.config.pad_token_id = model.config.eos_token_id
model.cuda()
model.eval();

# %% ../03_large.ipynb 8
def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    return generate(model, tokenizer, seq_length, prompt, length, num_samples, allow_linebreak)
