# AUTOGENERATED! DO NOT EDIT! File to edit: ../07_lawa.ipynb.

# %% auto 0
__all__ = ['model_path', 'full_path', 'tokenizer', 'model', 'seq_length', 'device', 'get_sample']

# %% ../07_lawa.ipynb 3
from os import getenv
model_path = getenv("MODEL")
from .gen import generate


# %% ../07_lawa.ipynb 5
from transformers import AutoModelForCausalLM, PreTrainedTokenizerFast
full_path = f'./models/{model_path}'
tokenizer = PreTrainedTokenizerFast.from_pretrained(full_path)
model = AutoModelForCausalLM.from_pretrained(
    full_path,
    #device_map="auto",
    torch_dtype='auto'
).eval()


# %% ../07_lawa.ipynb 6
import torch

seq_length = 1024
device='cuda'
model.to(device);
model.eval();

# %% ../07_lawa.ipynb 9
from front.common import process_seq

def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool, temperature:float=0.5):
    lm_text = prompt
    input_ids=torch.tensor([tokenizer.encode(lm_text)]).cuda()
    output_ids = model.generate(input_ids, do_sample=True, temperature=temperature, repetition_penalty=5.0, typical_p=0.9, top_k=10, top_p=0.95, #watermark=False,
                        max_new_tokens=length, 
                        num_return_sequences=num_samples,)
    input_len = len(input_ids[0])
    output_ids = output_ids[:,input_len-1:]
    result = [tokenizer.decode(o[1:]).replace('\n', ' ') for o in output_ids]
    result = process_seq(result)
    return result

