# AUTOGENERATED! DO NOT EDIT! File to edit: ../07_lawa.ipynb.

# %% auto 0
__all__ = ['model_path', 'gpu_part', 'full_path', 'tokenizer', 'config', 'model_max_length', 'max_model_len', 'model',
           'stop_token_ids', 'line_enders', 'create_logit_bias', 'create_token_blocker', 'get_sampling_params',
           'get_sample']

# %% ../07_lawa.ipynb 3
from os import getenv
from vllm import LLM, SamplingParams
from transformers import AutoTokenizer,AutoConfig
from front.common import process_seq
import random
from .gen import get_line_enders, iftoken
model_path = getenv("MODEL")
gpu_part = int(getenv("gpu_fraction",20))/100

# %% ../07_lawa.ipynb 6
full_path = f'./models/{model_path}'
tokenizer = AutoTokenizer.from_pretrained(full_path)

# saving VRAM
config = AutoConfig.from_pretrained(full_path)
model_max_length = config.max_position_embeddings
max_model_len = min(4096, model_max_length)

model = LLM(model=full_path, dtype="bfloat16", device="cuda", gpu_memory_utilization=gpu_part, max_model_len=max_model_len
            , enable_chunked_prefill=True, max_num_batched_tokens=4,max_num_seqs=4,
            # ── additional VRAM savers ────────────────────────────────────────────
            kv_cache_dtype="fp8",     # 2× smaller KV cache (needs Hopper/Ada+CUDA 11.8) :contentReference[oaicite:1]{index=1}
            calculate_kv_scales=True, # on-the-fly scales if you didn't pre-calibrate
            swap_space=8,            # GiB of CPU RAM to spill rare long contexts)
)

# %% ../07_lawa.ipynb 8
stop_token_ids = iftoken(tokenizer, ['<|endoftext|>','|eot_id|','<|end_of_text|>','<|eot_id|>','<pad>'])
line_enders = get_line_enders(tokenizer)

def create_logit_bias(tokenizer, blocked_tokens, penalty: float = float('-inf')):
    """Return {token_id: bias} mapping to ‘hard-ban’ tokens in V1."""
    blocked_token_ids = iftoken(tokenizer, blocked_tokens)
    return {tid: penalty for tid in blocked_token_ids}

def create_token_blocker(tokenizer, blocked_tokens):
    blocked_token_ids = iftoken(tokenizer, blocked_tokens)
    
    def token_blocker(input_ids, scores):
        if scores.dim() == 2:
            scores[:, list(blocked_token_ids)] = -float('inf')
        elif scores.dim() == 1:
            scores[list(blocked_token_ids)] = -float('inf')
        else:
            raise ValueError(f"Unexpected score tensor shape: {scores.shape}")
        return scores
    
    return token_blocker

def get_sampling_params(tokenizer, length: int, num_samples: int, allow_linebreak: bool, temperature: float):
    blocked_tokens = ['?»',"».",'http://',',[','("','.]',' («',')','\u2004',']','(«','[', ' [', '(', ' (', '\xa0', '*', '­', '~', '_', '\\', '\uf04a', '\ufeff', '\u2028']
    if not allow_linebreak:
        blocked_tokens.extend(line_enders)
    
    logit_bias = create_logit_bias(tokenizer, blocked_tokens)
    token_blocker = create_token_blocker(tokenizer, blocked_tokens)

    return SamplingParams(
        max_tokens=length,
        n=num_samples,
        min_p=0.1,
        stop_token_ids=stop_token_ids,
        ignore_eos=True,
        logits_processors=[token_blocker],
        #logit_bias=logit_bias,
        repetition_penalty=2.,
        temperature=temperature,
        seed=random.randint(0, 1000000),
    )

# %% ../07_lawa.ipynb 10
def get_sample(prompt: str, length: int, num_samples: int, allow_linebreak: bool, temperature: float = 1.0):
    max_input = model.llm_engine.model_config.max_model_len - length
    prompt = tokenizer.decode(tokenizer.encode(prompt)[-max_input:]).removeprefix('<|begin_of_text|>')
    sampling_params = get_sampling_params(tokenizer, length, num_samples, allow_linebreak, temperature)
    outputs = model.generate(prompt, sampling_params)
    generated_sequences = [oo.text for o in outputs for oo in o.outputs]
    return process_seq(generated_sequences)
