# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_rest.ipynb.

# %% auto 0
__all__ = ['singleton', 'model_path', 'seq_length', 'tokenizer', 'model', 'lock', 'get_sample']

# %% ../03_rest.ipynb 3
from .core import init_instance, generate
singleton, model_path = init_instance()

# %% ../03_rest.ipynb 5
seq_length = 1024

model_path = f'./models/large/{model_path}'
import torch
from transformers import GPT2LMHeadModel,GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained(model_path, pad_token_id = 50256)
model = GPT2LMHeadModel.from_pretrained(model_path,torch_dtype=torch.bfloat16) #.half()
model.config.pad_token_id = model.config.eos_token_id
model.cuda()
model.eval();

# %% ../03_rest.ipynb 7
import threading
lock = threading.RLock()

def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    with lock:
        return generate(model, tokenizer, seq_length, prompt, length, num_samples, allow_linebreak)
