# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_restXL.ipynb.

# %% auto 0
__all__ = ['singleton', 'model_path', 'seq_length', 'model', 'tokenizer', 'ds_engine', 'get_sample', 'bad_points', 'bad_words']

# %% ../04_restXL.ipynb 4
from .core import init_instance, generate
singleton, model_path = init_instance()

# %% ../04_restXL.ipynb 5
seq_length = 512

from src.xl_wrapper import RuGPT3XL
model = RuGPT3XL.from_pretrained(
    "sberbank-ai/rugpt3xl",
    weights_path=f"./models/xl/{model_path}.model",
    deepspeed_config_path="src/deepspeed_config/gpt3_xl_sparse_2048.json",
    seq_len=seq_length
)
tokenizer = model.tokenizer
model.cuda()
model.eval();

# %% ../04_restXL.ipynb 7
import deepspeed, torch
ds_engine = deepspeed.init_inference(model,
                                 mp_size=1,
                                 dtype=torch.half,
                                 checkpoint=None,
                                 replace_method='auto',
                                 replace_with_kernel_inject=True)
model = ds_engine.module

# %% ../04_restXL.ipynb 8
def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    return generate(model, tokenizer, seq_length, prompt, length, num_samples, allow_linebreak)

# %% ../04_restXL.ipynb 10
def bad_points(tokenizer, point):
    result = []
    for i in range(3, 30):
        code = tokenizer.encode(point*i)
        if len(code) == 1:
            result += [code]
    return result

def bad_words(tokenizer, allow_linebreak):
    bad_symbols = ['[','(','\xa0','<|endoftext|>','*','­', '~', '_', '\\', '\n\n', '\uf04a']
    bad_words_ids = [tokenizer.encode(s) for s in bad_symbols]
    for point in ['.','*','_','-']:
        bad_words_ids += bad_points(tokenizer, point)
    linebreaks = [tokenizer.encode(s) for s in ['\n', ' \n']]
    bad_words_ids += [] if allow_linebreak else linebreaks
    return bad_words_ids
