# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_restproxy.ipynb.

# %% auto 0
__all__ = ['singleton', 'model_path', 'seq_length', 'client', 'get_sample']

# %% ../04_restproxy.ipynb 3
from .core import init_instance, generate
singleton, model_path = init_instance()

# %% ../04_restproxy.ipynb 4
seq_length = 1024

# %% ../04_restproxy.ipynb 7
from text_generation import Client

client = Client("http://127.0.0.1:999")

def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    lm_text = '<LM>'+prompt
    result = client.generate(prompt, temperature=.5, repetition_penalty=5.0, typical_p=0.9, 
                       max_new_tokens=length, ).generated_text
    return [result]
