# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_restproxy.ipynb.

# %% auto 0
__all__ = ['seq_length', 'client', 'get_sample']

# %% ../04_restproxy.ipynb 3
from .core import process_seq

# %% ../04_restproxy.ipynb 4
seq_length = 1024

# %% ../04_restproxy.ipynb 6
from text_generation import Client

client = Client("http://127.0.0.1:999")

def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    lm_text = '<LM>'+prompt
    result = client.generate(lm_text, do_sample=True, temperature=.5, repetition_penalty=5.0, typical_p=0.9, top_k=10, top_p=0.95, watermark=False,
                       max_new_tokens=length, ).generated_text.replace('\n', ' ')
    
    result = process_seq([result])
    print(result)
    return result
