# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_restLAMA.ipynb.

# %% auto 0
__all__ = ['singleton', 'model_path', 'seq_length']

# %% ../04_restLAMA.ipynb 3
from .core import init_instance, generate
singleton, model_path = init_instance()

# %% ../04_restLAMA.ipynb 4
seq_length = 1024
