# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_storage.ipynb.

# %% auto 0
__all__ = ['THREADS_NUM', 'engine', 'session_maker', 'connection', 'metadata', 'logs']

# %% ../01_storage.ipynb 1
THREADS_NUM = 10
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
engine = create_engine('postgresql+psycopg2://postgres:rlp4ZKc6oC0OzgK1FSsJ@localhost:5535', pool_size=THREADS_NUM+2)
session_maker = sessionmaker(bind=engine, autocommit=False)
connection = engine.connect()
from sqlalchemy.exc import IntegrityError
from sqlalchemy.dialects.postgresql import insert, ARRAY, REAL
from sqlalchemy import Table, Column, LargeBinary, DateTime, Integer, String, MetaData, ForeignKey, update, func, delete, select

# %% ../01_storage.ipynb 2
metadata = MetaData()

# %% ../01_storage.ipynb 3
logs = Table('logs', metadata,
     Column('created', DateTime, nullable=False, server_default=func.current_timestamp()),
     Column('ip', String, ),
     Column('origin', String, ),
     Column('agent', String, ),
     Column('fs', String, ),
     Column('ff', String, ),
     Column('session', String, ),
     Column('type', Integer, ),
     Column('hash', String, ),
     Column('log', String, ),
)

# %% ../01_storage.ipynb 4
metadata.create_all(engine)
