# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_XL.ipynb.

# %% auto 0
__all__ = ['model_path', 'tokenizer', 'seq_length', 'model', 'ds_engine', 'get_sample']

# %% ../04_XL.ipynb 3
from os import getenv
model_path = getenv("MODEL")
from .gen import generate

# %% ../04_XL.ipynb 5
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("./tokenizer/rugpt3xl.tokenizer", local_files_only=True)


# %% ../04_XL.ipynb 6
seq_length = 512

from src.xl_wrapper import RuGPT3XL
model = RuGPT3XL.from_pretrained(
    "sberbank-ai/rugpt3xl",
    weights_path=f"./models/{model_path}.model",
    deepspeed_config_path="src/deepspeed_config/gpt3_xl_2048.json",
    seq_len=seq_length,
)
tokenizer = model.tokenizer
model.cuda()
model.eval();

# %% ../04_XL.ipynb 9
import deepspeed, torch
ds_engine = deepspeed.init_inference(model,
                                 mp_size=1,
                                 dtype=torch.float16,
                                 checkpoint=None,
                                 replace_with_kernel_inject=True)
model = ds_engine.module

# %% ../04_XL.ipynb 10
def get_sample(prompt, length:int, num_samples:int, allow_linebreak:bool):
    return generate(model, tokenizer, seq_length, prompt, length, num_samples, allow_linebreak)
